### PR TITLE
Optimized CPU usage by merging the dx info strings into one

### PR DESCRIPTION
**Pull request by paa93**

### CODE REVIEW

**Comment by paa93** [comment]
That's pretty wierd. Anyway, a pull request has been created. Hopefully it reduces the CPU usage a little.

**Comment by hamdyjs** [comment]
Okay good I will check it out in an hour or so.

Where did you originally comment? Trying to figure out why it shows that you commented on my repo.

**Comment by paa93** [comment]
On the commit itself at the forked project. Even files and and individual lines can have comments in a commit, git is amazing isn't it :+1:

**Comment by hamdyjs** [comment]
It is. I will test it soon.

One thing I noticed is the commit messages, no offence intended, but they don't really follow the standards. Your commit message told me which file you edited, but so did the difference.

A better message would be: "Optimize CPU usage by merging the marker strings into one"
and "Add a check for the settings table"

I know this might not sound important to you, but I'm somewhat a perfectionist, and when I merge these are the commit messages I will see. If you know how to change it (actually familiar with the process of changing a commit message) then please do it, if not, I will happily do it.

Thanks for your contributions, will test this very soon.

**Comment by paa93** [comment]
Good point, I noticed that after posting the pull request and couldn't figure out how to change it easily from the web interface.

**Comment by hamdyjs** [comment]
Take a look at the result:

mta-screen_2015-03-20_23-52-32

It doesn't look as good as the separate dx texts, but I get the optimization. The question here whether such optimization will make a difference or not. What do you think?

I also added the convertNumber function which was missing, fixed a couple of variables typo.

**Comment by hamdyjs** [comment]
Moved to #7 as I needed to push some changes

**Comment by paa93** [comment]
It makes difference for clients mainly, which can be seen in the performance browser. The point with this optimization however was to avoid calling functions like those who get screen coordinates from world position or draw framed text multiple times as it's inside the event "onClientRender" which may be triggered up to 60 times/second something that could make even the best CPU's drop in FPS which is sad as this is a great system. 

Also let's not forget the loop inside this event where ipairs is used, pairs will work as well as it's a non indexed table, pairs is faster as the order of the items doesn't matter. Another thing that may be optimized is line 26 where the distance to the text is checked. Why getting marker data before knowing if it's needed (core.client.lua:line 22). Say that we have a server with 200 business properties, that's over 1000 calls to getElementData in a second, even only one of them are close enough to show it's information.

I might post another pull request in a few days based on changes in v1.3 rather than trying to merge from v1.2, as many variable names and stuff is different now. Most optimization can be done in that "onClientRender" function at core.client.lua:line 19 anyway however.

**Comment by hamdyjs** [comment]
You can pull the pr/gtwopt branch, this has your changes plus all the v1.3 changes.

This code is somewhat old (2011 or 2012), back then I didn't really care about performance (or even know much), and the new update only focuses on OOP and the new dx ui.

I get your point. One of the ways we could improve it is to not use a timer for each business (for payout) but instead use a unified timer that checks if payout should be given, then calculate how many payouts should be given (if for example a business pays every 30 minutes and we're using an hour timer, so it should pay twice then). This can improve performance as timers are not really efficient.

Feel free to add/edit whatever you want and then open a PR, just make sure that the commit messages follow the standards, a simple Google search would help.

Thanks for your contributions! :+1:

**Pull request closed without merging**
